def check_dna_motif(dna_sequence, motif):
    positions = []
    motif_length = len(motif)

    if motif_length == 0 or len(dna_sequence) < motif_length:
        raise ValueError(
            "Motif must be non-empty and shorter than the DNA sequence.")

    for i in range(len(dna_sequence) - motif_length + 1):
        if dna_sequence[i:i + motif_length] == motif:
            positions.append(i + 1)

    return positions


result = check_dna_motif("TTACTCAATAAATACTCAATACTCAATTACTCAAATACTCAACTTACTCAATACTCAATACTCAAATGTACTCAATACTCAATTCTATCTACTCAACTACTCAAGTACTCAAATACTCAACGCGCTACTCAACGGACCCTACTCAATACTCAATTACTCAATACTCAATCCCATACTCAATACTCAATTACTCAAGGTGTACTCAAAGTACTCAAAAGCATACTCAACGATAAGTACTCAACTACTCAAATACTCAATACTCAAAGTACTCAACCCTGTCGACCTATACTCAAATACTCAAATCAGGTACTCAATACTCAATACTCAATAGAGTACTCAATACTCAATACTCAAAGTACTCAATACTCAACTTTACTCAAAGTACTCAATACTCAATTACTCAACTACTCAATACTCAAAATCCAGTACTCAACGGGTATACTCAAGGAGAAGCCCTGAAGTTTACTCAACATACTCAACTACTCAAGTCTTACTCAATACTCAACCCTTTACTCAATTACTCAAAAGGTACTCAAGCAAGACTACTCAATACTCAAATTACTCAACTACTCAATACTCAAGTACTCAAGTACTCAATACTCAATATACTCAACTACTCAATTACTCAAGGCTACTCAACATACTCAAGTATACTCAATACTCAAGAATACTCAACATACTCAATACTCAAGGTACTCAATATACTCAAATACTCAAACTACTCAATATACTCAACGATTACTCAATACTCAATGTGATCGCTACTCAATCGAACGTACTCAATACTCAAGCTTCTTAACCCTACTTTAGCTTACTCAACTACTCAATATACTCAAAGC", "TACTCAATA")
print(" ".join(map(str, result)))
