from helper.extract_fasta_seqences import extract_fasta_sequences
from P8_translating_RNA_into_protein import translate_rna_to_protein


def rna_splicing(fasta_sequence):
    sequences_dict = extract_fasta_sequences(fasta_sequence)
    sequences_list = list(sequences_dict.values())
    dna_sequence = sequences_list[0]
    exon_sequences = sequences_list[1:]

    for exon in exon_sequences:
        if exon in dna_sequence:
            dna_sequence = dna_sequence.replace(exon, '')

    mrna_sequence = dna_sequence.replace('T', 'U')
    protein_sequence = translate_rna_to_protein(mrna_sequence)

    return protein_sequence


if __name__ == "__main__":
    fasta_sequence = """>Rosalind_0928
ATGAATAGAGAAAAGTATCCGAAGATGGTCCCGAGAAGACCTCCACCCGACCGCCGATAA
CATCCACCCACTTAGATGACAGCGGAAGAATCCGCGACTGCTTGCTAGGTTGAGCTGTTC
GCCAGATCGCGCCGCGTGTACTGGTGTGATTCTTTTCCCTTGGTTCGTTCTGTTCGGTGT
ATCCACTGGCCCCCAATCGACCTCATTTGGGTTTCGCTGGACTCTACGTGCCGTTTACCC
GGCATATGCCGGTAGGGAGGGATATCATAAATGTCATGTGCGCGGGCTGTCTGGCCACTC
CGAGATGCAGAAATCGGGGAGCCATGGACTTCTTCGCACATCGGTTTAGTTGATGACTAA
ACCCTACATGGTCACTCCAATACTCTGCAAGCGGCTGAAAAGCGACTTCGCTCAGACCGC
CCGACAAGCTTGGAAAAGGTGGAATCCGGTCGCGAAGTGGGGCCCACGATGGACGGTAAC
GGTAACACAATGAACGTCCAACGATCTTTGTGTGGGCGCCTCGTCCCAAATACTGCTACT
GCTCGACTACCAGATTGCGCCATGCATAAGGGCTTTGTTACGTCGTTCGGGATCCCCAAA
AGAAGACTAATGATGCCTCATACATTGGCCTTGCGCCGAATTTTTAGTGGGCTATCTCAC
TATCTAGGCTGTCAATCGGGAAGCCAACTTTGCCTATCTTCCACACAAGTTTCCAAGCTC
TTAGTACCGTAGCTTACAGACTACATCCGGCGGCTGTCGGTCCACGGAAGTCTCATGTTT
TGTGCCCCTCAGTGCAACGTTTTGCACGTTTCCCCAAATCGTTTCAGACGCGGCACTACA
TCATAACTATGTCGCTTTCGTTTGCGTGCTCCTTTGACCATTTACGTCTCCCCGACTGCG
TTCGCTACATACGATCATTAA
>Rosalind_3501
TACATCATAA
>Rosalind_1734
ACACAAGTTTCCAAGCTCTT
>Rosalind_5105
GGGCCCACGATG
>Rosalind_8393
ACCATTTACGTCTCCCCG
>Rosalind_0507
GCGGCTGAAAAGCGACTT
>Rosalind_3111
CTAGGTTGAGCTGTTCGCCAGATCGCGCC
>Rosalind_3974
TGGTTCGTTCTGTTCGGTGTAT
>Rosalind_0172
TTGGGTTTCGCTGGACTCTA
>Rosalind_7978
GGACTTCTTCGCACATCGGTTTAGTTGATGACTAA
>Rosalind_0886
TGTGGGCGCCTCGTCCCAAATACTGCTACTGCTCGACTACCAGATTGCG
>Rosalind_5664
CCAAAAGAAGACTAATGATGCCTCATACATTGGCCTTGCGCCGAATTTTT
>Rosalind_7172
GGATATCATAAATGTCATGTG
>Rosalind_9230
CCGAAGATGGTCCCGAGAAGACCTCCACCCGACCGCCGATAACA
>Rosalind_6614
AAGTCTCATGTTTTGTGCCCCTCAGTGCAACGTTTT
"""
    result = rna_splicing(fasta_sequence)
    print(result)
