from helper.extract_fasta_seqences import extract_fasta_sequences


def find_splice_motif(dna_sequence_s, dna_sequence_t):
    position_collection = []
    for i in range(len(dna_sequence_t)):
        for j in range(len(dna_sequence_s)):
            if len(position_collection) == 0 or j > position_collection[-1]:
                if dna_sequence_t[i] == dna_sequence_s[j]:
                    position_collection.append(j+1)
                    break

    if len(position_collection) == len(dna_sequence_t):
        return position_collection
    else:
        return []


if __name__ == "__main__":
    fasta_file_contents = """>Rosalind_8555
TCTTATAGAGAGCACTACGATTCCGGCGGACGATTGAGGTTAATTCCTCATCGCCAAGCT
AACAGAATCCGCCGGAAGGCGACGAGAGTGAATTTAATTCTTGGGTCCTGCCGTATGACG
AGCATGCTAACCTCAACTCACGTAGGATAGACTGCATAATATCTCACGGTGGATATTGAT
GAGCGCTTACGGACGACCCAAGTTACCGAACATTATATCGGGACAGGGGTCGACCGAGGG
AGCGCCCATAGCCCGTTGTTTATACAGACGTGAGTAGTAGACCCACTGACCAATTTGTGC
TTGACGTTCAGATCCCTTGAACAGTGTCTGTGCCAGGCCTACTCCTGGACTGATATGCTA
CAGGTCTCTGGTACCCCGCGCCGCCCAGCTCTACCTCCATTTGTACTCGTTTCGATGGAC
ATAGTTCATTTGTACAGTGACCAGCCTTGCCGTTCCTTCCAGGATCCTATTAGGCGATTT
GAAGATGCTAAAAGGGTCTAACGAAACCGATGTCTCCTCCAATCTTACTCCCGCGCTCAC
AACCTCTGGTAGCTCACCCATACCCAAGACGCACAATGCACCTAATGCTATCGGTTGGAG
CGAGTAGCCTAATCGATGGGGTGATCCACCGCACAAATTCCTCGCCGCCAGAAAAACTCC
CGACTTGGGCACGGCTGATGTATTGCACAGAGTTGTCACATGCCAAGTGCCTAGCGGGGG
TGGACCCGGTCGGACGAGGTGGCAGCATTGTCACTTCGTTTGCTAGCCACCGGAGTCCGC
AGTTCATAATAACGAAGGCGCTCTAACACGCTAAAAACTGTATTAAACCTCCCGTTGTAA
GTGCCACTGGTGTTACTAGGTTTCAGACCCTCCGGTTGTTCTGGCACGTGACGTCTTTGA
CAAGAGCGTGGGCAAAGTTTATCTTAT
>Rosalind_6349
TAACATTCACTCTTACCTGGAGTTTAG"""

    dna_sequence_list = list(extract_fasta_sequences(fasta_file_contents).values())
    positions = find_splice_motif(dna_sequence_list[0], dna_sequence_list[1])
    print(" ".join(map(str, positions)))
