from helper.extract_fasta_seqences import extract_fasta_sequences


def handle_raw_input(raw_input):
    sequence_dict = extract_fasta_sequences(raw_input)
    sequence_list = list(sequence_dict.values())

    return sequence_list[0], sequence_list[1]


def check_transition_tranversion(nucleotide_1, nucleotide_2):
    if nucleotide_1 == nucleotide_2:
        return False

    if nucleotide_1 in ["A", "G"]:
        if nucleotide_2 in ["T", "C"]:
            return "transversion"
        else:
            return "transitions"

    if nucleotide_1 in ["T", "C"]:
        if nucleotide_2 in ["A", "G"]:
            return "transversion"
        else:
            return "transitions"


def calculate_transition_transversion_ratio(sequence_1, sequence_2):
    if len(sequence_1) != len(sequence_2):
        return None

    tranversion_count = 0
    transiton_count = 0
    for i in range(len(sequence_1)):
        check_result = check_transition_tranversion(sequence_1[i], sequence_2[i])
        if not check_result:
            continue
        elif check_result == "transitions":
            transiton_count += 1
        else:
            tranversion_count += 1

    return transiton_count / tranversion_count


if __name__ == "__main__":
    raw_input = """>Rosalind_8544
ACTCCGTCGCGCCAACTCTGCTACAATGTGGGTAGGGTACCGCAACGAGGGTTTCAGGGG
ACGGCCCGACGAATCTCCATACGAGTTAGGGTGAAGCGTGTATTACTTCATTTGATGAAT
ACTGTGAAACCGTTCGCCCTGCTCGGGTTTTGCTTCCAGGTGTATACCGGGGGATGATGC
GTATGCAGTCGGGAGCTCCCAGCCTCAGTGTATAATGTACCGCGTTTTGCATCACGCACT
CCTCGTCGTTTTGCGGCATCATCAACCCGCCTTTTTATTTAAGTGACAGTTCGCAAGAGG
GTACATCTCACGCCTCGTGAGGGGTTAAATCTGTCTCCTAATTGTTCGACCATGAGCGCA
AACTGAATTCCTGTATTCAGGGAAATGCGTCGTACACCCCATGTTGGGTCGAGCTGCTGC
GAACTAAAGGCCACCACAGATGGAATCTGGTGAGAGCCAAGCAACGTTCATCCACTCAGT
GCTGACCTGTTAAACTGCAGCGCTGGAGACAACTCACTGACCCCCCGGGATGACGTACAT
CCTGTTCTGGGGACGTTGTTCGGCCCATGTGTTATGGTCAGGCCGGGCGCGCTTAGTCGC
GTCTGAATTACCCAGAGGCATACAAATCATCGCAGTGGCTGCAACCGGTTACTCCGGTCA
CATCTGCAGCCGCATGGCGTCAGTGCGGGCCCCGAGTACTGGCGGCGGGCACAGTTAGGG
TGAACGCACGCGCGTTTGCGAGCTACGATCGTCCTGGCTGATGGAGCGAATGTCGACATT
TCGGCAAGCCATCTACCAGTGGAATGCATCTTCTGAGGACTCCTGCGTCCGGAGCGATAG
GCACTTGAATAGCGCAAAGGTC
>Rosalind_1079
AATTCGTGACGTAAACTCTGCTATAATGTAGGTGAGGAACTACGCCAAGGTTTTCAGAGA
ACGGTTGGATGAATCTTCGAACGAGTTCGAGTCTGACGAGTATTACTTCATCTAATGATC
ACTGGCAAAATGTTCGCACTGGACGAGCTTTGTTTGTACGTATATATCGGCCGATGATAC
GTATGCAGTCGGGAACCCTCCGTCCCGGGATACAACAGTTCGCATTTAGCACAACGTGCT
CTTCGTCGCTTTGCGGTACTACCAACCAACCATTTTATTTAAGTTCCAGTCCGGAGGACC
GTACGTTGGATGCCTCGTGATGGATTAAGATCGTCTTCAAGTCGGTCGGCCATGGGCGTA
AACTGAGTTTTTGTATCCAGAGAAGTGGGCAGTACACCCCGTGTCGAGTTAGGCCATTAC
GATTCCAGGGTAACTCCAGATGGAAGCTGGCGAGAACCCAGCAGCGTTCGCTCCCCCGAT
GCTAACTTGCTAAGGCGCCGTGCTGAGGTTACCTCACCGACCCCCCGGGGTCCCTTATAT
CCTGTTCTGATGACACTGTTCGGCCCATGTGTCGTGGTCGAACCAGGTGCATTCCGACGA
GTCCTAGTCACCTAAAGTCACACAAATCAACGCAATTGTATGAGCCGGCTACTTCGATGA
TTTTTCCAATTGCATGGTGTCAACACGTGCCCCGAGCTCTGACAGCGCGTAGAGTTGGGG
TTAAGACCGGCGCGTTTGCGACCTACGATCGCTCTGCTCGATCGAACGAGTAACAGCGTC
TTGACGAACCATCTACCAGTGGAGTGCATCTCCTTAGGTTTCCTGGGTCCGGAAAGATAG
GCGCTAAAACAGTGCAAAGCAT"""

    sequence_1, sequence_2 = handle_raw_input(raw_input)
    print(calculate_transition_transversion_ratio(sequence_1, sequence_2))
